import './globals.css';

export const metadata = {
  title: 'Code-flix',
  description: 'Generated by Code-flix',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='bg-[#141414] text-white scrollbar-hide'>{children}</body>
    </html>
  );
}